<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Voucher_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get voucher by id
     */
    function get_voucher($id)
    {
        return $this->db->get_where('vouchers',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all vouchers count
     */
    function get_all_vouchers_count()
    {
        $this->db->from('vouchers');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all vouchers
     */
    function get_all_vouchers($params = array())
    {
        $this->db->select('vouchers.*, stores.store_name, stores.store_crm_code');
        
        $this->db->join('stores', 'stores.id=vouchers.store_id', 'left');
        $this->db->order_by('id', 'desc');
        // if(isset($params) && !empty($params))
        // {
        //     $this->db->limit($params['limit'], $params['offset']);
        // }
        return $this->db->get('vouchers')->result_array();
    }
        
    /*
     * function to add new voucher
     */
    function add_voucher($params)
    {
        $this->db->insert('vouchers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update voucher
     */
    function update_voucher($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('vouchers',$params);
    }
    
    /*
     * function to delete voucher
     */
    function delete_voucher($id)
    {
        return $this->db->delete('vouchers',array('id'=>$id));
    }
}